POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email":"test@gmail.com",
    "username":"test",
    "password":"123456"
}   

### Login Route

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"123456"
}

### Refresh Token

POST http://localhost:5000/api/auth/refreshToken   
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQxOTU1NjYsImV4cCI6MTY2NTc1MzE2NiwiYXVkIjoiNjE2N2Q0OGE3Yjg3ZTkzZTI4YTcxOGYwIiwiaXNzIjoiaW5zdGFncmFtLmNvbSJ9.y1gA0boDtOmgRLJ6SaJhaG9T_CSM6Eh-n9NmK2LA2NQ"
}


### Logout

POST http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQxOTQ5MDUsImV4cCI6MTY2NTc1MjUwNSwiYXVkIjoiNjE2N2Q0OGE3Yjg3ZTkzZTI4YTcxOGYwIiwiaXNzIjoiaW5zdGFncmFtLmNvbSJ9.9Gdy69u-yCWnVUcXwlGSnrPIN_HZZ65uiwxoXZTWcto"
}

### Get a user using token 

GET http://localhost:5000/api/auth/user
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzQxOTU1NzUsImV4cCI6MTYzNDE5NTYwNSwiYXVkIjoiNjE2N2Q0OGE3Yjg3ZTkzZTI4YTcxOGYwIiwiaXNzIjoiaW5zdGFncmFtLmNvbSJ9.v9Ce3feTeQ2d8xhtn_4MxW8rarI-kCveJSeOHfhkt7c